# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

accumarray_rcpp <- function(subs, val, sz = NULL, fillval = 0) {
    .Call(`_ScatterDensity_accumarray_rcpp`, subs, val, sz, fillval)
}

c_inPSphere2D <- function(data, xBinNr, yBinNr, nrXBins, nrYBins, nrData, paretoRadius) {
    .Call(`_ScatterDensity_c_inPSphere2D`, data, xBinNr, yBinNr, nrXBins, nrYBins, nrData, paretoRadius)
}

c_inPSphere2D_parallel <- function(data, xBinNr, yBinNr, nrXBins, nrYBins, nrData, paretoRadius) {
    .Call(`_ScatterDensity_c_inPSphere2D_parallel`, data, xBinNr, yBinNr, nrXBins, nrYBins, nrData, paretoRadius)
}

quantile4LargeVectors <- function(x, probs) {
    .Call(`_ScatterDensity_quantile4LargeVectors`, x, probs)
}

smooth1D_C <- function(Y, lambda, na_rm = FALSE, Silent = FALSE) {
    .Call(`_ScatterDensity_smooth1D_C`, Y, lambda, na_rm, Silent)
}

smooth1D_parallel <- function(G, lambda, nbins, smooth_rows = TRUE, na_rm = FALSE, Silent = FALSE) {
    .Call(`_ScatterDensity_smooth1D_parallel`, G, lambda, nbins, smooth_rows, na_rm, Silent)
}

